### ISSUE TITLE
ImageMagick module not available with this PHP installation. 

### ISSUE THREAD

**Issue by ImaCrea** [YunoHost-Apps/pixelfed_ynh#119]
I managed somehow to have a couple of pics uploaded. They appear in the feed but not in the preview area.
Just checked the logs and apparently there's an issue with ImageMagick :/

```
[2020-09-27 21:09:02] production.ERROR: ImageMagick module not available with this PHP installation. {"exception":"[object] (Intervention\\Image\\Exception\\NotSupportedException(code: 0): ImageMagick module not available with this PHP installation. at /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/Imagick/Driver.php:20)
[stacktrace]
#0 /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/ImageManager.php(112): Intervention\\Image\\Imagick\\Driver->__construct()
#1 /var/www/pixelfed/vendor/intervention/image/src/Intervention/Image/ImageManager.php(54): Intervention\\Image\\ImageManager->createDriver()
#2 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Intervention\\Image\\ImageManager->make('/var/www/pixelf...')
#3 /var/www/pixelfed/app/Util/Media/Image.php(113): Illuminate\\Support\\Facades\\Facade::__callStatic('make', Array)
#4 /var/www/pixelfed/app/Util/Media/Image.php(93): App\\Util\\Media\\Image->handleImageTransform(Object(App\\Media), false)
#5 /var/www/pixelfed/app/Util/Media/Image.php(81): App\\Util\\Media\\Image->handleResizeImage(Object(App\\Media))
#6 /var/www/pixelfed/app/Jobs/ImageOptimizePipeline/ImageResize.php(54): App\\Util\\Media\\Image->resizeImage(Object(App\\Media))
#7 [internal function]: App\\Jobs\\ImageOptimizePipeline\\ImageResize->handle()
#8 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#14 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize))
#15 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize))
#16 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize), false)
#18 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize))
#19 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize))
#20 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#21 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(App\\Jobs\\ImageOptimizePipeline\\ImageResize))
#22 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#23 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(354): Illuminate\\Queue\\Jobs\\Job->fire()
#24 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(300): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#25 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#26 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#27 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#28 /var/www/pixelfed/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#29 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#30 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#31 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#33 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#34 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#35 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#36 /var/www/pixelfed/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#37 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#38 /var/www/pixelfed/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /var/www/pixelfed/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /var/www/pixelfed/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /var/www/pixelfed/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/pixelfed/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 {main}
"} 
```

**Comment by ImaCrea** [comment]
Hence, there's no preview available.
![Capture d’écran 2020-09-27 à 23 14 29](https://user-images.githubusercontent.com/764332/94375910-36c9c300-0117-11eb-9c57-16a2000ed91a.png)

**Comment by ImaCrea** [comment]
Did some research here. I found in that documentation https://docs.pixelfed.org/install-guides/arch.html#preparing-a-machine that we should do that :

![Capture d’écran 2020-10-03 à 17 00 06](https://user-images.githubusercontent.com/764332/94994742-fbf1e000-0599-11eb-8266-2107d38a0e07.png)

But I can't find such file in ```/etc/php/7.3/fpm/conf.d/```

Not sure where else to go :/
